CREATE TABLE [dbo].[AspNetUsers](
	[Id] [uniqueidentifier] NOT NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[IsApproved] [bit] NOT NULL,
	[FirstName] [nvarchar] (100) NULL,
	[LastName]  [nvarchar] (100) NULL,
	[DisplayName] [nvarchar](256) NULL,
	[SelectedIssueColumns]  [nvarchar] (50) NULL,
	[IssuesPageSize] [int] NULL,
	[PreferredLocale] [nvarchar](50) NULL,
	[ReceiveEmailNotifications] [bit]  CONSTRAINT [DF_BugNet_AspNetUsers_RecieveEmailNotifications] DEFAULT ((1)) NOT NULL,
	CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ( [Id] ASC) 
);