//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exceptions", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add role.
        /// </summary>
        internal static string AddRoleError {
            get {
                return ResourceManager.GetString("AddRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured deleting an IssueAttachment.
        /// </summary>
        internal static string AttachmentDeleteError {
            get {
                return ResourceManager.GetString("AttachmentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not clone project.
        /// </summary>
        internal static string CloneProjectError {
            get {
                return ResourceManager.GetString("CloneProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new upload folder {0} for project {1}.
        /// </summary>
        internal static string CreateProjectUploadFolderError {
            get {
                return ResourceManager.GetString("CreateProjectUploadFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured accessing the database.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete custom field.
        /// </summary>
        internal static string DeleteCustomFieldError {
            get {
                return ResourceManager.GetString("DeleteCustomFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete issue type.
        /// </summary>
        internal static string DeleteIssueTypeError {
            get {
                return ResourceManager.GetString("DeleteIssueTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be deleted because it is assigned to one or more issues.  You will need to re-assign these issues to a different {1} before it can be deleted!.
        /// </summary>
        internal static string DeleteItemAssignedToIssueError {
            get {
                return ResourceManager.GetString("DeleteItemAssignedToIssueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete mailbox.
        /// </summary>
        internal static string DeleteMailboxError {
            get {
                return ResourceManager.GetString("DeleteMailboxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete milestone.
        /// </summary>
        internal static string DeleteMilestoneError {
            get {
                return ResourceManager.GetString("DeleteMilestoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete priority.
        /// </summary>
        internal static string DeletePriorityError {
            get {
                return ResourceManager.GetString("DeletePriorityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete upload folder {0} for project id {1}.
        /// </summary>
        internal static string DeleteProjectUploadFolderError {
            get {
                return ResourceManager.GetString("DeleteProjectUploadFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete resolution.
        /// </summary>
        internal static string DeleteResolutionError {
            get {
                return ResourceManager.GetString("DeleteResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete role.
        /// </summary>
        internal static string DeleteRoleError {
            get {
                return ResourceManager.GetString("DeleteRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete status.
        /// </summary>
        internal static string DeleteStatusError {
            get {
                return ResourceManager.GetString("DeleteStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting this user..
        /// </summary>
        internal static string DeleteUserError {
            get {
                return ResourceManager.GetString("DeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file you have selected is invalid..
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not meet the allowed file types..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied issue id [{0}] is not valid..
        /// </summary>
        internal static string InvalidIssueId {
            get {
                return ResourceManager.GetString("InvalidIssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied project id [{0}] is not valid..
        /// </summary>
        internal static string InvalidProjectId {
            get {
                return ResourceManager.GetString("InvalidProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied issue id or BugNET id is invalid.
        /// </summary>
        internal static string InvalidQuickSearchText {
            get {
                return ResourceManager.GetString("InvalidQuickSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository name was not formated correctlly. Only alpha-numeric charaters, \&quot;-\&quot;, and \&quot;_\&quot; are allowed..
        /// </summary>
        internal static string InvalidRepositoryName {
            get {
                return ResourceManager.GetString("InvalidRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag name was not formated correctlly. Only alpha-numeric charaters, \&quot;-\&quot;, and \&quot;_\&quot; are allowed..
        /// </summary>
        internal static string InvalidRepositoryTagName {
            get {
                return ResourceManager.GetString("InvalidRepositoryTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured in processing the mailbox reader..
        /// </summary>
        internal static string MailboxReaderError {
            get {
                return ResourceManager.GetString("MailboxReaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search value cannot be blank, please enter either an issue id or a BugNET id.
        /// </summary>
        internal static string MissingQuickSearchText {
            get {
                return ResourceManager.GetString("MissingQuickSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password could not be changed, please verify that the password meets the password requirements..
        /// </summary>
        internal static string PasswordChangeError {
            get {
                return ResourceManager.GetString("PasswordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password error.
        /// </summary>
        internal static string PasswordResetError {
            get {
                return ResourceManager.GetString("PasswordResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating the profile.
        /// </summary>
        internal static string ProfileUpdateError {
            get {
                return ResourceManager.GetString("ProfileUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} does not have permission to this project..
        /// </summary>
        internal static string ProjectAccessDenied {
            get {
                return ResourceManager.GetString("ProjectAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found for project id [{0}]..
        /// </summary>
        internal static string ProjectNotFoundError {
            get {
                return ResourceManager.GetString("ProjectNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user querystring parameter is not properly formed.
        /// </summary>
        internal static string QueryStringError {
            get {
                return ResourceManager.GetString("QueryStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment is required to create a tag.
        /// </summary>
        internal static string RepositoryCommentRequired {
            get {
                return ResourceManager.GetString("RepositoryCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save project, please verify that the data is correct..
        /// </summary>
        internal static string RepositoryProjectSaveError {
            get {
                return ResourceManager.GetString("RepositoryProjectSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the attachment {0}..
        /// </summary>
        internal static string SaveAttachmentError {
            get {
                return ResourceManager.GetString("SaveAttachmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save custom field.
        /// </summary>
        internal static string SaveCustomFieldError {
            get {
                return ResourceManager.GetString("SaveCustomFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save issue custom fields.
        /// </summary>
        internal static string SaveCustomFieldValuesError {
            get {
                return ResourceManager.GetString("SaveCustomFieldValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the issue..
        /// </summary>
        internal static string SaveIssueError {
            get {
                return ResourceManager.GetString("SaveIssueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save issue type.
        /// </summary>
        internal static string SaveIssueTypeError {
            get {
                return ResourceManager.GetString("SaveIssueTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save issue vote.
        /// </summary>
        internal static string SaveIssueVoteError {
            get {
                return ResourceManager.GetString("SaveIssueVoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save milestone.
        /// </summary>
        internal static string SaveMilestoneError {
            get {
                return ResourceManager.GetString("SaveMilestoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save priority.
        /// </summary>
        internal static string SavePriorityError {
            get {
                return ResourceManager.GetString("SavePriorityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save project, please verify that the project name and code are unique values..
        /// </summary>
        internal static string SaveProjectError {
            get {
                return ResourceManager.GetString("SaveProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save resolution.
        /// </summary>
        internal static string SaveResolutionError {
            get {
                return ResourceManager.GetString("SaveResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save status.
        /// </summary>
        internal static string SaveStatusError {
            get {
                return ResourceManager.GetString("SaveStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating this user..
        /// </summary>
        internal static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload path is invalid..
        /// </summary>
        internal static string UploadPathInvalid {
            get {
                return ResourceManager.GetString("UploadPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project upload path has not been defined for project {0}..
        /// </summary>
        internal static string UploadPathNotDefined {
            get {
                return ResourceManager.GetString("UploadPathNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload directory {0} can not be found. Please check with the administrator that the directory exists on the web server..
        /// </summary>
        internal static string UploadPathNotFound {
            get {
                return ResourceManager.GetString("UploadPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error authorizing this user..
        /// </summary>
        internal static string UserAuthorizedError {
            get {
                return ResourceManager.GetString("UserAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error unauthorizing this user..
        /// </summary>
        internal static string UserUnAuthorizedError {
            get {
                return ResourceManager.GetString("UserUnAuthorizedError", resourceCulture);
            }
        }
    }
}
