//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notifications", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\ForgotPassword.xslt.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\ForgotPassword.xslt.
        /// </summary>
        internal static string ForgotPasswordHTML {
            get {
                return ResourceManager.GetString("ForgotPasswordHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\IssueAdded.xslt.
        /// </summary>
        internal static string IssueAdded {
            get {
                return ResourceManager.GetString("IssueAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\IssueAdded.xslt.
        /// </summary>
        internal static string IssueAddedHTML {
            get {
                return ResourceManager.GetString("IssueAddedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue {0} has been added to a project you are monitoring..
        /// </summary>
        internal static string IssueAddedSubject {
            get {
                return ResourceManager.GetString("IssueAddedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\IssueUpdated.xslt.
        /// </summary>
        internal static string IssueUpdated {
            get {
                return ResourceManager.GetString("IssueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\IssueUpdated.xslt.
        /// </summary>
        internal static string IssueUpdatedHTML {
            get {
                return ResourceManager.GetString("IssueUpdatedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue {0} has been updated by {1}.
        /// </summary>
        internal static string IssueUpdatedSubject {
            get {
                return ResourceManager.GetString("IssueUpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\IssueUpdatedWithChanges.xslt.
        /// </summary>
        internal static string IssueUpdatedWithChanges {
            get {
                return ResourceManager.GetString("IssueUpdatedWithChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\IssueUpdatedWithChanges.xslt.
        /// </summary>
        internal static string IssueUpdatedWithChangesHTML {
            get {
                return ResourceManager.GetString("IssueUpdatedWithChangesHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\NewAssignee.xslt.
        /// </summary>
        internal static string NewAssignee {
            get {
                return ResourceManager.GetString("NewAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML\NewAssignee.xslt.
        /// </summary>
        internal static string NewAssigneeHTML {
            get {
                return ResourceManager.GetString("NewAssigneeHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue {0} has been assigned to you.
        /// </summary>
        internal static string NewAssigneeSubject {
            get {
                return ResourceManager.GetString("NewAssigneeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\NewIssueComment.xslt.
        /// </summary>
        internal static string NewIssueComment {
            get {
                return ResourceManager.GetString("NewIssueComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\NewIssueComment.xslt.
        /// </summary>
        internal static string NewIssueCommentHTML {
            get {
                return ResourceManager.GetString("NewIssueCommentHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue {0} has a new comment.
        /// </summary>
        internal static string NewIssueCommentSubject {
            get {
                return ResourceManager.GetString("NewIssueCommentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reminder.
        /// </summary>
        internal static string PasswordReminderSubject {
            get {
                return ResourceManager.GetString("PasswordReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\PasswordReset.xslt.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML\PasswordReset.xslt.
        /// </summary>
        internal static string PasswordResetHTML {
            get {
                return ResourceManager.GetString("PasswordResetHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        internal static string PasswordResetSubject {
            get {
                return ResourceManager.GetString("PasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\UserRegistered.xslt.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\UserRegistered.xslt.
        /// </summary>
        internal static string UserRegisteredHTML {
            get {
                return ResourceManager.GetString("UserRegisteredHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registration.
        /// </summary>
        internal static string UserRegisteredSubject {
            get {
                return ResourceManager.GetString("UserRegisteredSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text\UserVerification.xslt.
        /// </summary>
        internal static string UserVerification {
            get {
                return ResourceManager.GetString("UserVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html\UserVerification.xslt.
        /// </summary>
        internal static string UserVerificationHTML {
            get {
                return ResourceManager.GetString("UserVerificationHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to activate your new account....
        /// </summary>
        internal static string UserVerificationSubject {
            get {
                return ResourceManager.GetString("UserVerificationSubject", resourceCulture);
            }
        }
    }
}
