//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.6.339.0")]
[assembly: AssemblyFileVersion("1.6.339.0")]
[assembly: AssemblyProduct("BugNET")]
[assembly: ComVisible(false)]
[assembly: AssemblyCompany("http://www.bugnetproject.com")]
[assembly: AssemblyCopyright("Copyright © 2006-2013 BugNET Project")]
[assembly: AssemblyConfiguration("net-4.0.win32")]